export const tottenhamPlayer = [
  {
    id: 1,
    korName: "요리스",
    engName: "Lloris",
    number: 1,
    flagSrc: "/flag/France.svg",
    playerImgSrc: "/player/tottenham/Lloris.png",
  },
  {
    id: 2,
    korName: "올리버 스킵",
    engName: "Skipp",
    number: 4,
    flagSrc: "/flag/England.svg",
    playerImgSrc: "/player/tottenham/Skipp.png",
  },
  {
    id: 3,
    korName: "호이비에르",
    engName: "Højbjerg",
    number: 5,
    flagSrc: "/flag/Denmark.svg",
    playerImgSrc: "/player/tottenham/Højbjerg.png",
  },
  {
    id: 4,
    korName: "손흥민",
    engName: "Son",
    number: 7,
    flagSrc: "/flag/Korea.svg",
    playerImgSrc: "/player/tottenham/Son.png",
  },
  {
    id: 5,
    korName: "비수마",
    engName: "Bissouma",
    number: 8,
    flagSrc: "/flag/Mali.svg",
    playerImgSrc: "/player/tottenham/Bissouma.png",
  },
  {
    id: 6,
    korName: "히샬리송",
    engName: "Richarlison",
    number: 9,
    flagSrc: "/flag/Brazil.svg",
    playerImgSrc: "/player/tottenham/Richarlison.png",
  },
  {
    id: 7,
    korName: "매디슨",
    engName: "Maddison",
    number: 10,
    flagSrc: "/flag/England.svg",
    playerImgSrc: "/player/tottenham/Maddison.png",
  },
  {
    id: 8,
    korName: "브리안",
    engName: "Bryan",
    number: 11,
    flagSrc: "/flag/Spain.svg",
    playerImgSrc: "/player/tottenham/Bryan.png",
  },
  {
    id: 9,
    korName: "에메르송",
    engName: "Royal",
    number: 12,
    flagSrc: "/flag/Brazil.svg",
    playerImgSrc: "/player/tottenham/Royal.png",
  },
  {
    id: 10,
    korName: "비카리오",
    engName: "Vicario",
    number: 13,
    flagSrc: "/flag/Italy.svg",
    playerImgSrc: "/player/tottenham/Vicario.png",
  },
  {
    id: 11,
    korName: "페리시치",
    engName: "Perisic",
    number: 14,
    flagSrc: "/flag/Croatia.svg",
    playerImgSrc: "/player/tottenham/Perisic.png",
  },
  {
    id: 12,
    korName: "에릭 다이어",
    engName: "Dier",
    number: 15,
    flagSrc: "/flag/England.svg",
    playerImgSrc: "/player/tottenham/Dier.png",
  },
  {
    id: 13,
    korName: "로메로",
    engName: "Romero",
    number: 17,
    flagSrc: "/flag/Argentina.svg",
    playerImgSrc: "/player/tottenham/Romero.png",
  },
  {
    id: 14,
    korName: "로셀소",
    engName: "Lo Celso",
    number: 18,
    flagSrc: "/flag/Argentina.svg",
    playerImgSrc: "/player/tottenham/LoCelso.png",
  },
  {
    id: 15,
    korName: "세세뇽",
    engName: "Sessegnon",
    number: 19,
    flagSrc: "/flag/England.svg",
    playerImgSrc: "/player/tottenham/Sessegnon.png",
  },
  {
    id: 16,
    korName: "포스터",
    engName: "Forster",
    number: 20,
    flagSrc: "/flag/England.svg",
    playerImgSrc: "/player/tottenham/Forster.png",
  },
  {
    id: 17,
    korName: "쿨루셉스키",
    engName: "Kulusevski",
    number: 21,
    flagSrc: "/flag/Sweden.svg",
    playerImgSrc: "/player/tottenham/Kulusevski.png",
  },
  {
    id: 18,
    korName: "브레넌 존슨",
    engName: "Johnson",
    number: 22,
    flagSrc: "/flag/Wales.svg",
    playerImgSrc: "/player/tottenham/Johnson.png",
  },
  {
    id: 19,
    korName: "페드로 포로",
    engName: "Pedro Porro",
    number: 23,
    flagSrc: "/flag/Spain.svg",
    playerImgSrc: "/player/tottenham/PedroPorro.png",
  },
  {
    id: 20,
    korName: "솔로몬",
    engName: "Solomon",
    number: 27,
    flagSrc: "/flag/Israel.svg",
    playerImgSrc: "/player/tottenham/Solomon.png",
  },
  {
    id: 21,
    korName: "파페 사르",
    engName: "Sarr",
    number: 29,
    flagSrc: "/flag/Senegal.svg",
    playerImgSrc: "/player/tottenham/Sarr.png",
  },
  {
    id: 22,
    korName: "벤탄쿠르",
    engName: "Bentancur",
    number: 30,
    flagSrc: "/flag/Uruguay.svg",
    playerImgSrc: "/player/tottenham/Bentancur.png",
  },
  {
    id: 23,
    korName: "벤 데이비스",
    engName: "Davies",
    number: 33,
    flagSrc: "/flag/Wales.svg",
    playerImgSrc: "/player/tottenham/Davies.png",
  },
  {
    id: 24,
    korName: "필립스",
    engName: "Phillips",
    number: 35,
    flagSrc: "/flag/England.svg",
    playerImgSrc: "/player/tottenham/Phillips.png",
  },
  {
    id: 25,
    korName: "벨리스",
    engName: "Veliz",
    number: 36,
    flagSrc: "/flag/Argentina.svg",
    playerImgSrc: "/player/tottenham/Veliz.png",
  },
  {
    id: 26,
    korName: "판더펜",
    engName: "van de Ven",
    number: 37,
    flagSrc: "/flag/Argentina.svg",
    playerImgSrc: "/player/tottenham/vandeVen.png",
  },
  {
    id: 27,
    korName: "우도기",
    engName: "Udogie",
    number: 38,
    flagSrc: "/flag/Italy.svg",
    playerImgSrc: "/player/tottenham/Udogie.png",
  },
  {
    id: 28,
    korName: "오스틴",
    engName: "Austin",
    number: 40,
    flagSrc: "/flag/England.svg",
    playerImgSrc: "/player/tottenham/Austin.png",
  },
  {
    id: 29,
    korName: "화이트먼",
    engName: "Whiteman",
    number: 41,
    flagSrc: "/flag/England.svg",
    playerImgSrc: "/player/tottenham/Whiteman.png",
  },
];
